### ISSUE TITLE
Error packing Sigil/Sigil II MP3 soundtrack?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Owlet7/wadfusion#10]
As said in #9, Only Helion works for me, however... the Sigil I & SIGIL II soundtrack MP3 wads doesn't work, or atleast, are incorrectly integrated.
The script does correctly notice them and set the right settings to enable them in the final doom_complete.pk3 wad.
```
Helion v0.9.4.0 
Processor:  X64 
Processors: 12 
OS: Unix 6.10.7.200 x64 (running x64) 
Could not load SoundFont SoundFonts/Default.sf2. 
System.Exception: Failed to generate an audio buffer.
   at Helion.Client.Music.AudioStream..ctor(Int32 sampleRate, Int32 channelCount, Int32 latency, Int32 blockLength) in /home/pm/Documents/Helion/Client/Music/AudioStream.cs:line 94
--- End of stack trace from previous location ---
   at Helion.Client.Music.AudioStream..ctor(Int32 sampleRate, Int32 channelCount, Int32 latency, Int32 blockLength) in /home/pm/Documents/Helion/Client/Music/AudioStream.cs:line 118
   at Helion.Client.Music.AudioStreamFactory.GetOutputStream(Int32 sampleRate, Int32 channelCount) in /home/pm/Documents/Helion/Client/Music/AudioStream.cs:line 14
   at Helion.Client.Music.FluidSynthMusicPlayer.OutputChanged() in /home/pm/Documents/Helion/Client/Music/FluidSynthMusicPlayer.cs:line 178
   at Helion.Client.Music.FluidSynthMusicPlayer.EnsureSoundFont(String soundFontPath) in /home/pm/Documents/Helion/Client/Music/FluidSynthMusicPlayer.cs:line 154 
CheckOpenGLSupport 45 
OpenGL v4.6 
OpenGL Shading Language: 4.60 
OpenGL Vendor: AMD 
OpenGL Hardware: AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 18.1.6, DRM 3.57, 6.10.7-200.fsync.fc40.x86_64) 
OpenGL Extensions: 241 
GL_ARB_clip_control True 
MapPersistentBit True 
MapInfo: Unknown map item: InterMusic line:5 
MapInfo: Unknown map item: BorderTexture line:6 
MapInfo: Unknown map item: InterMusic line:19 
MapInfo: Unknown map item: BorderTexture line:20 
MapInfo: Unknown map item: InterMusic line:6 
MapInfo: Unknown map item: InterMusic line:6 
MapInfo: Unknown map item: InterMusic line:9 
MapInfo: Unknown map item: BorderTexture line:12 
MapInfo: Unknown map item: InterMusic line:9 
MapInfo: Unknown map item: BorderTexture line:12 
MapInfo: Unknown map item: InterMusic line:6 
MapInfo: Unknown gameinfo item: AddEventHandlers line:31 
MapInfo: Unknown gameinfo item: StatusBarClass line:32 
Error parsing text on line 8, offset -1. Hit end of file when expecting data. 
Error parsing text on line 0, offset 10. Expected = but got , 
Error parsing text on line 357, offset 12. Unknown animdefs type firetexture 
// doom 1 and lagacy of rust switch texture replacements 
^ 
Building nodes [/tmp/tmp2secAy.tmp]... 
Completed nodes 00:00:00.1226141 
Loading compiled map... 
Completed map load 00:00:00.0196757 
Cannot find music track:  
```
[wadfusion.log](https://github.com/user-attachments/files/17047179/wadfusion.log)
Here's the wadfusion log to study. Notice the `.mp3.mus` being added for the mp3 files. Don't have any zdoom knowledge, but that seems incorrect with zmusic.

**Comment by Owlet7** [comment]
This is working as intended, WadFusion renames those files after extracting them (`rename_mp3()`), and Sigil uses ZScript to set music in WadFusion. The Helion source port is not supported.

**Comment by PoorPocketsMcNewHold** [comment]
I thought it was odd, as testing Sigil with the sountrack iwad separately worked. I'll deal with #9 first to test it on GzDoom. I did planned on reporting it to their repo instead, but since it worked fine with the original wads, and used the already stable zmusic, I've reported it here first.

-------- Message d'origine --------

**Comment by Owlet7** [comment]
The difference between the original WADs and WF's doom_complete.pk3 is that in order to achieve switching Sigil soundtracks on the fly, and without the wrong music playing for a split second when the level loads, we have it start music playback entirely through ZScript, which only GZDoom supports.

WadFusion, and WadSmoosh before it, also uses ZScript to replace conflicting textures between Doom 1 / Doom 2 / Final Doom, and to implement the new weapons from Legacy of Rust, etc., so it could only work with GZDoom. Reporting it as an issue to other ports wouldn't be productive.
